feat: component to create a user
Minibuz/Banxxy pull request #20
Opened 2023-01-16 21:26 UTC by franncisca

feat: user creation component

2023-01-16 21:46 UTC, Minibuz approved these changes

2023-01-17 08:43 UTC, MaksDUT requested changes

2023-01-17 08:43 UTC, MaksDUT commented on frontend/src/services/user.create.js
> +                if (response.data.accessToken){
Il y a pas besoin de récuperer de token pour la créeation de compte

2023-01-17 08:43 UTC, MaksDUT commented on frontend/src/views/HelloWorld.vue
> +    @click="goTo('/userCreation')"
on va passer par une modal plutot qu'une nouvelle page routé

2023-01-17 09:13 UTC, Robin-Loup approved these changes

2023-01-17 20:09 UTC, GuillaumeDOMART approved these changes

2023-01-18 09:24 UTC, MaksDUT approved these changes
on peut avancer avec l'issue pour le moment, on va enlever les console dans les futures modifications

2023-01-18 09:24 UTC, merged