fix: user back
Minibuz/Banxxy pull request #21
Opened 2023-01-16 22:16 UTC by GuillaumeDOMART

2023-01-16 23:14 UTC, Minibuz approved these changes
Juste ta méthode, getDependantUser je trouve qu'elle est un peu grosse, on pourrais la diviser en plusieurs fonctions

2023-01-17 08:11 UTC, MaksDUT approved these changes

2023-01-17 08:38 UTC, Jsisie requested changes
Le nom de tes méthodes "isAdvisor" et "isCustomer" insinue que tu renvoies un boolean, ça serait plutôt "getAdvisor" et "getCustomer" logiquement

2023-01-17 13:15 UTC, Jsisie approved these changes
nice

2023-01-17 13:15 UTC, merged