Transaction service #62
Minibuz/Banxxy pull request #65
Opened 2023-01-24 21:53 UTC by Robin-Loup

2023-01-24 21:58 UTC, Jsisie reviewed
Dans TransactionController, si tu reçois true le HttpStatus doit être à 200 mais si tu reçois false tu doit renvoyer un code d'erreur.

2023-01-24 22:00 UTC, Jsisie reviewed
Si tu as un TransactionsController avec un s, tu dois avoir un service et serviceImpl Transactions correspondant

2023-01-24 22:02 UTC, Jsisie requested changes
Fix les 2 commentaires au-dessus

2023-01-25 20:42 UTC, Jsisie approved these changes

2023-01-25 20:44 UTC, Minibuz approved these changes

2023-01-25 21:57 UTC, GuillaumeDOMART approved these changes

2023-01-25 21:58 UTC, merged