User management
Minibuz/Banxxy pull request #68
Opened 2023-01-25 19:35 UTC by GuillaumeDOMART

2023-01-25 20:23 UTC, Minibuz requested changes

2023-01-25 20:23 UTC, Minibuz commented on backend/src/main/java/fr/esipe/banxxy/service/impl/AccountServiceImpl.java
> +    private final EmailSenderServiceImpl emailSenderService;
Utiliser l'interface, pas l'implémentation

2023-01-25 20:23 UTC, Minibuz commented on backend/src/main/java/fr/esipe/banxxy/service/impl/AccountServiceImpl.java
>                  if (customer.getAccounts().removeIf(account -> account.getId().equals(Long.valueOf(accountId)))) {
Pourquoi ne pas faire une seule fois Long.valueOf(accountId) et le mettre dans une variable au lieu de le faire 3 fois ?

2023-01-25 20:23 UTC, Minibuz commented on backend/src/main/java/fr/esipe/banxxy/service/impl/UserServicesImpl.java
> +    private final EmailSenderServiceImpl emailSenderService;
Utiliser l'interface, pas l'implémentation

2023-01-26 19:12 UTC, Robin-Loup approved these changes

2023-01-26 21:14 UTC, Minibuz approved these changes

2023-01-26 21:14 UTC, Jsisie approved these changes

2023-01-26 21:14 UTC, merged